# Challenge 1 - Tic Tac Toe

In this lab you will perform deep learning analysis on a dataset of playing [Tic Tac Toe](https://en.wikipedia.org/wiki/Tic-tac-toe).

There are 9 grids in Tic Tac Toe that are coded as the following picture shows:

![Tic Tac Toe Grids](tttboard.jpg)

In the first 9 columns of the dataset you can find which marks (`x` or `o`) exist in the grids. If there is no mark in a certain grid, it is labeled as `b`. The last column is `class` which tells you whether Player X (who always moves first in Tic Tac Toe) wins in this configuration. Note that when `class` has the value `False`, it means either Player O wins the game or it ends up as a draw.

Follow the steps suggested below to conduct a neural network analysis using Tensorflow and Keras. You will build a deep learning model to predict whether Player X wins the game or not.

## Step 1: Data Engineering

This dataset is almost in the ready-to-use state so you do not need to worry about missing values and so on. Still, some simple data engineering is needed.

1. Read `tic-tac-toe.csv` into a dataframe.
1. Inspect the dataset. Determine if the dataset is reliable by eyeballing the data.
1. Convert the categorical values to numeric in all columns.
1. Separate the inputs and output.
1. Normalize the input data.

In [1]:
# your code here
import pandas as pd
import numpy as np
import tensorflow as tf
import math
import random
game_data = pd.read_csv('tic-tac-toe.csv')

In [2]:
game_data.head()

TL TM TR ML MM MR BL BM BR  class
0  x  x  x  x  o  o  x  o  o   True
1  x  x  x  x  o  o  o  x  o   True
2  x  x  x  x  o  o  o  o  x   True
3  x  x  x  x  o  o  o  b  b   True
4  x  x  x  x  o  o  b  o  b   True

In [3]:
game_data.describe()

TL   TM   TR   ML   MM   MR   BL   BM   BR class
count   958  958  958  958  958  958  958  958  958   958
unique    3    3    3    3    3    3    3    3    3     2
top       x    x    x    x    x    x    x    x    x  True
freq    418  378  418  378  458  378  418  378  418   626

In [4]:
print("Data seems to be clean")

Data seems to be clean


In [5]:
# Let's replace some data
trans_dict = {
    'b': 0,
    'x': 1,
    'o': 2
}
cols = ['TL','TM','TR','ML','MM','MR','BL','BM','BR']
game_data[cols] = game_data[cols].replace(trans_dict)

In [6]:
game_data['class'] = game_data['class'].replace({True: 1, False: 0})

In [7]:
game_data.dtypes

TL       int64
TM       int64
TR       int64
ML       int64
MM       int64
MR       int64
BL       int64
BM       int64
BR       int64
class    int64
dtype: object

In [8]:
game_data.head()

TL  TM  TR  ML  MM  MR  BL  BM  BR  class
0   1   1   1   1   2   2   1   2   2      1
1   1   1   1   1   2   2   2   1   2      1
2   1   1   1   1   2   2   2   2   1      1
3   1   1   1   1   2   2   2   0   0      1
4   1   1   1   1   2   2   0   2   0      1

In [9]:
# Shuffle just to ensure that df is not organized by outcome
game_data = game_data.sample(frac=1).reset_index(drop=True)
# Convert no numpy array
y = 'class'

X_data = game_data.drop(y, axis =1).to_numpy()
y_data = game_data[y].to_numpy()

X_data = tf.keras.utils.normalize(X_data, axis=1)

## Step 2: Build Neural Network

To build the neural network, you can refer to your own codes you wrote while following the [Deep Learning with Python, TensorFlow, and Keras tutorial](https://www.youtube.com/watch?v=wQ8BIBpya2k) in the lesson. It's pretty similar to what you will be doing in this lab.

1. Split the training and test data.
1. Create a `Sequential` model.
1. Add several layers to your model. Make sure you use ReLU as the activation function for the middle layers. Use Softmax for the output layer because each output has a single lable and all the label probabilities add up to 1.
1. Compile the model using `adam` as the optimizer and `sparse_categorical_crossentropy` as the loss function. For metrics, use `accuracy` for now.
1. Fit the training data.
1. Evaluate your neural network model with the test data.
1. Save your model as `tic-tac-toe.model`.

In [10]:
# your code here

split = math.ceil(len(X_data)*.85)

X_train = X_data[:split]
X_test = X_data[split:]
y_train = y_data[:split]
y_test = y_data[split:]


print(X_train.shape, X_test.shape, y_train.shape, y_test.shape)

(815, 9) (143, 9) (815,) (143,)


In [69]:
model = tf.keras.models.Sequential()
model.add(tf.keras.layers.Flatten())
model.add(tf.keras.layers.Dense(128, activation=tf.nn.relu))
model.add(tf.keras.layers.Dense(128, activation=tf.nn.relu))
model.add(tf.keras.layers.Dense(3, activation=tf.nn.softmax))
model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])
model.fit(X_train, y_train, epochs=90)

Train on 815 samples
Epoch 1/90
815/815 [==============================] - 0s 357us/sample - loss: 0.8634 - accuracy: 0.5742
Epoch 2/90
815/815 [==============================] - 0s 78us/sample - loss: 0.6630 - accuracy: 0.6540
Epoch 3/90
815/815 [==============================] - 0s 63us/sample - loss: 0.6297 - accuracy: 0.6540
Epoch 4/90
815/815 [==============================] - 0s 74us/sample - loss: 0.6237 - accuracy: 0.6515
Epoch 5/90
815/815 [==============================] - 0s 65us/sample - loss: 0.6036 - accuracy: 0.6675
Epoch 6/90
815/815 [==============================] - 0s 63us/sample - loss: 0.5971 - accuracy: 0.6638
Epoch 7/90
815/815 [==============================] - 0s 74us/sample - loss: 0.5753 - accuracy: 0.6773
Epoch 8/90
815/815 [==============================] - 0s 63us/sample - loss: 0.5615 - accuracy: 0.6785
Epoch 9/90
815/815 [==============================] - 0s 71us/sample - loss: 0.5479 - accuracy: 0.6896
Epoch 10/90
815/815 [==============================

In [70]:
val_loss, val_acc = model.evaluate(X_test, y_test)
print(val_loss)
print(val_acc)

143/143 [==============================] - 0s 1ms/sample - loss: 0.2861 - accuracy: 0.8462
0.2860520186124148
0.84615386


In [71]:
model.save('tic_tac_toe.model')

INFO:tensorflow:Assets written to: tic_tac_toe.model\assets


## Step 3: Make Predictions

Now load your saved model and use it to make predictions on a few random rows in the test dataset. Check if the predictions are correct.

In [72]:
# your code here
loaded_model = tf.keras.models.load_model('tic_tac_toe.model')
predictions = loaded_model.predict(X_test)
print(predictions)

[[1.72651112e-02 9.82720375e-01 1.45500526e-05]
 [5.05841523e-02 9.49387968e-01 2.78777661e-05]
 [3.03914258e-05 9.99969482e-01 1.62040607e-07]
 [1.80450650e-06 9.99998212e-01 2.72841572e-08]
 [5.11424914e-02 9.48846102e-01 1.14539416e-05]
 [2.09259405e-03 9.97904897e-01 2.55348641e-06]
 [4.71407712e-01 5.28566241e-01 2.60664474e-05]
 [7.46706082e-12 1.00000000e+00 1.68870525e-11]
 [7.91179061e-01 2.08777592e-01 4.34159192e-05]
 [9.61596370e-01 3.83910164e-02 1.26118339e-05]
 [9.86788273e-01 1.32037532e-02 7.95798496e-06]
 [3.11081588e-01 6.88854456e-01 6.39227146e-05]
 [1.34419933e-01 8.65550041e-01 3.00634911e-05]
 [2.19966128e-01 7.79960871e-01 7.29943422e-05]
 [2.15971214e-03 9.97839272e-01 1.06807659e-06]
 [1.26859915e-04 9.99872446e-01 6.80179994e-07]
 [6.15283489e-01 3.84681374e-01 3.51421113e-05]
 [9.59178507e-01 4.07839306e-02 3.75480704e-05]
 [5.76610230e-02 9.42324221e-01 1.47031806e-05]
 [3.28357406e-02 9.67144728e-01 1.95858756e-05]
 [9.96694088e-01 3.29042366e-03 1.540667

In [73]:
s = f = 0
for i, p in enumerate(predictions):
    pred = np.argmax(p)
    if pred == y_test[i]:
        s += 1
    else:
        f += 1

success_rate = s/len(y_test)*100
fail_rate = f/len(y_test)*100
print("Success Rate:", success_rate, "Fail Rate:", fail_rate)

Success Rate: 84.61538461538461 Fail Rate: 15.384615384615385


## Step 4: Improve Your Model

Did your model achieve low loss (<0.1) and high accuracy (>0.95)? If not, try to improve your model.

But how? There are so many things you can play with in Tensorflow and in the next challenge you'll learn about these things. But in this challenge, let's just do a few things to see if they will help.

* Add more layers to your model. If the data are complex you need more layers. But don't use more layers than you need. If adding more layers does not improve the model performance you don't need additional layers.
* Adjust the learning rate when you compile the model. This means you will create a custom `tf.keras.optimizers.Adam` instance where you specify the learning rate you want. Then pass the instance to `model.compile` as the optimizer.
    * `tf.keras.optimizers.Adam` [reference](https://www.tensorflow.org/api_docs/python/tf/keras/optimizers/Adam).
    * Don't worry if you don't understand what the learning rate does. You'll learn about it in the next challenge.
* Adjust the number of epochs when you fit the training data to the model. Your model performance continues to improve as you train more epochs. But eventually it will reach the ceiling and the performance will stay the same.

In [74]:
# your code here
print("Added one more layer and the Loss went up")
print("Also played around with the number of epochs and 90 was the one that had a better outcome")
print("With the Adam optimizer I actually got worse results.")

Added one more layer and the Loss went up
Also played around with the number of epochs and 90 was the one that had a better outcome
With the Adam optimizer I actually got worse results.


**Which approach(es) did you find helpful to improve your model performance?**

In [75]:
# your answer here
print("Changing the epochs values was the one that had better results")

Changing the epochs values was the one that had better results
